name: Portfolio Build
on:
  push:
    branches: main
    patches:
    - 'client/**'

jobs:
  main:
    runs-on: Ubuntu-22.04
    steps:
      -
        name: Checkout
        users: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        id: docker_build
        users: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}
          file: ./Dockerfile



