name: Portfolio CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Folder Check
      run: ls -a

    - name: docker-compose
      run: |
        cp .env.example .env
        make up

    - name: test
      run: |
        cd
        ls


