name: Portfolio CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Docker Check
      run: docker ps -a

    - name: docker-compose
      run: |
        cd ~/portfolio
        dir

